import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import './../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Cognifusion',
    description: 'Generated by BrigthPath',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
            }}>
            <html lang="en">
                <body className={inter.className}>
                    <ReduxProvider>
                        {children}
                    </ReduxProvider></body>
            </html>
        </ClerkProvider>
    )
}

