import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "CogniFusion",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider appearance={{
            variables: { colorPrimary: '#624cf5' }
        }}>
            <html lang="en">
                <body className={`${inter.className} bg-dark-1`}>
                    <ReduxProvider>{children} </ReduxProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}